package:
- name: SOIC
  alignment:
  - name: Aligned, multiple rows
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
  - name: Alternate, multiple rows
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
  - name: Aligned, single row
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
  - name: Alternate, single row
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
- name: QUAD
  alignment:
  - name: Aligned, multiple rows
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
  - name: Alternate, multiple rows
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
  - name: Aligned, single row
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
  - name: Alternate, single row
    direction:
    - name: Inside
      image: inside.svg
    - name: Outside
      image: outside.svg
    - name: Both sides
      image: bothsides.svg
- name: BGA
  alignment:
  - name: Quadrant
    direction:
    - name: noname
      image: quadrant.svg
  - name: Diagonal
    direction:
    - name: TopLeft
      image: topleft.svg
    - name: TopRight
      image: topright.svg
    - name: BottomLeft
      image: bottomleft.svg
    - name: BottomRight
      image: bottomright.svg
  - name: X-pattern
    direction:
    - name: Counterclock
      image: counterclock.svg
    - name: Clockwise
      image: clockwise.svg
- name: BGA staggered
  alignment:
  - name: noname
    direction:
    - name: Horizontal
      image: horizontal.svg
    - name: Vertical
      image: vertical.svg